# Generated by Django 3.2.8 on 2021-10-18 19:13

import author.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=512)),
                ('avatar', models.ImageField(blank=True, upload_to=author.models.author_avatar_path)),
                ('bio', models.TextField()),
                ('date_of_birth', models.DateField(blank=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=255)),
                ('interested_in', models.JSONField(default=list)),
                ('phone', models.CharField(max_length=20)),
                ('role', multiselectfield.db.fields.MultiSelectField(choices=[('member', 'Member'), ('author', 'Author'), ('editor', 'Editor'), ('admin', 'Administrator')], default='member', max_length=26)),
                ('social_link', models.JSONField(default=dict)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
